Models/PhoneBook.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABSA_CIB_Digital_Tech___Assessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneBook
    {
        public string Name { get; set; }
        public long PhoneNumber { get; set; }
    }
}

Models/PhoneBookViewModel.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Web;

namespace ABSA_CIB_Digital_Tech___Assessment.Models
{
    public class PhoneBookViewModel
    {
        public string Name { get; set; }
        public int ID { get; set; }

        public int PhoneNumber { get; set; }
    }
    public class PhonebookDetails
    {
        public List<PhoneBook> Search(List<string>info)
        {

            StringBuilder buildSql = new StringBuilder();
            buildSql.Append("SELECT * FROM PhoneBook WHERE ");
            foreach(string value in info)
            {
                buildSql.AppendFormat("Name = '{0}'", value); 
            }
            string datasql = buildSql.ToString();
            return QueryList(datasql);
        }

        protected List<PhoneBook> QueryList(string name)
        {
            List<PhoneBook> lst = new List<PhoneBook>();
            SqlCommand cmd = GenerateSqlcommand(name);
            using (cmd.Connection)
            {
                SqlDataReader reader = cmd.ExecuteReader();
                if(reader.HasRows)
                {
                    while(reader.Read())
                    {
                        lst.Add(ReadValue(reader));
                    }
                }
            }
            return lst;
        }

        private PhoneBook ReadValue(SqlDataReader reader)
        {
            PhoneBook dt = new PhoneBook();
            dt.Name = (String)reader["Name"];
            dt.PhoneNumber = Convert.ToInt32(reader["PhoneNumber"]);
            return dt;
        }

        private SqlCommand GenerateSqlcommand(string cmdTest)
        { 
            string constring = ConfigurationManager.ConnectionStrings["ABSAEntitie"].ToString();
            SqlConnection con = new  SqlConnection(constring);
            SqlCommand cmd = new SqlCommand(cmdTest,con);
            cmd.Connection.Open();
            return cmd;
        }
    }

}

Controllers/PhoneBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using ABSA_CIB_Digital_Tech___Assessment.Models;
using ABSA_CIB_Digital_Tech___Assessment.Repository;

namespace ABSA_CIB_Digital_Tech___Assessment.Controllers
{
    public class PhoneBookController : Controller
    {
        ABSAEntities Entities = new ABSAEntities();
        protected List<string> info = new List<string>();
        
        // GET: PhoneBook
        [HttpPost]
        public ActionResult Index(string name)
        {
            try
            {
                if (name != "")
                {
                   
                    string[] phonebk = name.Trim().Split(new string[] { "" }, StringSplitOptions.RemoveEmptyEntries);
                    this.info = phonebk.ToList();
                    PhonebookDetails access = new PhonebookDetails();
                    List<PhoneBook> collection = access.Search(this.info);
                    ViewBag.ListPhonebook = collection.ToList();// phonebk.ToList();
                    return View(collection);

                }
                else
                {

                    ViewBag.ListPhonebook = this.Entities.PhoneBooks.ToList();
                    ServiceRepository serviceObj = new ServiceRepository();
                    HttpResponseMessage response = serviceObj.GetResponse("api/ApiPhoneBook/GetAllPhoneBook");
                    response.EnsureSuccessStatusCode();
                    List<Models.PhoneBookViewModel> phonebk = response.Content.ReadAsAsync<List<Models.PhoneBookViewModel>>().Result;
                    ViewBag.Title = "All Phone Numbers";
                    return View(phonebk);
                }
            }
            catch (Exception)
            {
                throw;
            }

            
        }

        public ActionResult Index( )
        {


            try
            {
                ViewBag.ListPhonebook = this.Entities.PhoneBooks.ToList();
                ServiceRepository serviceObj = new ServiceRepository();
                HttpResponseMessage response = serviceObj.GetResponse("api/ApiPhoneBook/GetAllPhoneBook");
                response.EnsureSuccessStatusCode();
                List<Models.PhoneBook> phonebk = response.Content.ReadAsAsync<List<Models.PhoneBook>>().Result;
                ViewBag.Title = "All Phone Numbers";
                return View(phonebk);
            }
            catch (Exception)
            {
                throw;
            }


        }


        // GET: PhoneBook/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PhoneBook/Create
        public ActionResult Create( )
        {
            return View();
        }

        // POST: PhoneBook/Create

        [HttpPost]
        public ActionResult Create(PhoneBook phonebook)
        {

            ServiceRepository serviceObj = new ServiceRepository();
            HttpResponseMessage response = serviceObj.PostResponse("api/ApiPhoneBook/PostNewPhonebook", phonebook);
            response.EnsureSuccessStatusCode();
            return RedirectToAction("Index");

            }
            // GET: PhoneBook/Edit/5
            public ActionResult Edit(int id)
        {
            PhoneBookViewModel phonebook = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:44302/api/");
                //HTTP GET
                var responseTask = client.GetAsync("ApiPhonebook?id=" + id.ToString());
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<PhoneBookViewModel>();
                    readTask.Wait();
                    phonebook = readTask.Result;
                }
            }
            return View(phonebook);
        }

        // POST: PhoneBook/Edit/5
        [HttpPost]

        public ActionResult Edit(PhoneBookViewModel phonebook)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:44302/api/ApiPhonebook");
                //HTTP POST
                var putTask = client.PutAsJsonAsync<PhoneBookViewModel>("ApiPhonebook", phonebook);
                putTask.Wait();
                var result = putTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return RedirectToAction("Index");
                }
            }
            return View(phonebook);
        }
        // GET: PhoneBook/Delete/5
        public ActionResult Delete(string name)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:44302/api/");

                //HTTP DELETE
                var deleteTask = client.DeleteAsync("ApiPhonebook/" + name.ToString());
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }
    }
}

Views/PhoneBook/Create.cshtml
@model ABSA_CIB_Digital_Tech___Assessment.Models.PhoneBook

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PhoneBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/PhoneBook/Delete.cshtml
@model ABSA_CIB_Digital_Tech___Assessment.Models.PhoneBook

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PhoneBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/PhoneBook/Index.cshtml
@model IEnumerable<ABSA_CIB_Digital_Tech___Assessment.Models.PhoneBook>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Phone Book</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/scripts/jquery-3.4.1.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
    @* <link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@
    <script src="~/scripts/jquery.dataTables.min.js"></script>
    <script src="~/scripts/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#DataTable').DataTable();
            $('#checkBoxAll').click(function () {
                if ($(this).is(":checked")) {
                    $(".chkCheckBoxId").prop("checked", true)
                }
                else {
                    $(".chkCheckBoxId").prop("checked", false)
                }
            });
        });
    </script>
</head>

<body>
    <div class="container py-4">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h5>Phone Book</h5>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Index", "PhoneBook", FormMethod.Post))
                {
                    {
                        <p>
                            Find by name: @Html.TextBox("name")
                            <input id="btnSearch" type="submit" value="Search" />
                        </p>
                    }

                    <br /><br />
                    <table id="DataTable" style="width:100%;" class="table table-bordered">
                        <thead>
                            <tr>
                                <th><input type="checkbox" id="checkBoxAll" class="custom-checkbox" /></th>
                                <th>Name </th>
                                <th>Phone Number</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var phonebook in ViewBag.ListPhonebook)
                            {
                                <tr>
                                    <td><input type="checkbox" name="Name" value="@phonebook.Name" class="custom-checkbox chkCheckBoxId" /></td>
                                    <td>@phonebook.Name"</td>
                                    <td>@phonebook.PhoneNumber</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <button type="submit" value="Delete" class="btn btn-sm btn-danger rounded-0" onclick="return confirm('Are you sure you want to delete?')"><i class="fa fa-trash-o"></i> Delete</button>
                }
            </div>
        </div>
    </div>
</body>
</html>